name: "Deploy to Staging" # Name of the action.
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: cloud-projects-365117 # ID of the GCP project.
  DEPLOYMENT_NAME: delay-flights
  IMAGE: delay-flights
jobs:
  
  deployment:
    name: "Deploying"
   
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout" # Checkout the repository code.
        uses: "actions/checkout@v3"

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          project_id: cloud-projects-365117

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Build the Docker image
      - name: Build
        run: |-
          docker build \
            --tag "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA" \
            --no-cache \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push "gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA"
